// frontend/src/components/CardProduct.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import { AiFillEye, AiFillSignal, AiFillAppstore, AiTwotoneCalendar, AiOutlineStar, AiFillAlipayCircle, AiFillAmazonSquare, AiFillBank } from "react-icons/ai";
import './styles/CardProduct.css'

export default function CardProduct({ product }) {
    const { name, date, place, idproduct, description, price, tags, rating, thumbnailimg } = product;

    const renderTags = (tags) => {
        return tags.map((tag, index) => (
            <div key={index} className="mb-1">
                <AiFillEye /> {tag.tag_name}: {tag.tag_value}<br />
            </div>
        ));
    };

    return (
        <div className="cardProduct">
            <div className="card-image">
                <Link to={`/product/${idproduct}`}>
                    <img src={thumbnailimg} alt={name} />
                </Link>
            </div>
            <div className="card-body">
                <h6 className="card-title">
                    <Link to={`/product/${idproduct}`}>{name}</Link>
                </h6>
                <p className="card-info">
                    <AiFillAmazonSquare /> {description}<br />
                    <AiFillBank /> Price: {price}<br />
                    <AiTwotoneCalendar /> Date: {new Date(date).toLocaleDateString()}<br />
                    <AiFillSignal /> Place: {place}<br />
                    <AiFillSignal /> Rating: {rating}<br />
                </p>
                <div>
                    {renderTags(tags)}
                </div>
            </div>
        </div>
    );
}

// frontend-angular/src/app/components/card-product/card-product.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { Product } from '../../models/product.model';

@Component({
  selector: 'app-card-product',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './card-product.component.html',
  styleUrl: './card-product.component.css'
})
export class CardProductComponent {
  @Input() product!: Product;

  renderTags(tags: { tag_name: string; tag_value: string }[]) {
    return tags.map((tag, index) => ({
      ...tag,
      icon: 'visibility',
      index
    }));
  }
}

<!-- card-product.component.html -->
<div class="cardProduct">
  <div class="card-image">
    <a [routerLink]="['/product', product.idproduct]">
      <img [src]="product.thumbnailimg" [alt]="product.name" />
    </a>
  </div>
  <div class="card-body">
    <h6 class="card-title">
      <a [routerLink]="['/product', product.idproduct]">{{ product.name }}</a>
    </h6>
    <p class="card-info">
      {{ product.description }}<br />
      Price: {{ product.price }}<br />
      Date: {{ product.date | date }}<br />
      Place: {{ product.place }}<br />
      Rating: {{ product.rating }}<br />
    </p>
    <div *ngFor="let tag of product.tags; let i = index">
      {{ tag.tag_name }}: {{ tag.tag_value }}<br />
    </div>
  </div>
</div>
